# Generated by Django 5.1.3 on 2025-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhiliaoauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
    ]
